grafana/profiles-drilldown

- docs/CODE-ARCHITECTURE.md
- docs/CONTRIBUTING.md
Fixes https://github.com/grafana/explore-profiles/issues/55
Adding the "Code architecture" doc (which was private before) and some other small changes.
`-`
> docs: Update contribution guidelines

- docs/CONTRIBUTING.md
Update for grammar, product name, and links to doc. Added links to documentation for GitHub integration and for how to contribute to Explore Profiles doc. 
https://github.com/grafana/explore-profiles/issues/55
> docs: Update CONTRIBUTING.md

- src/pages/ProfilesExplorerView/SceneProfilesExplorer.tsx
- src/pages/ProfilesExplorerView/actions/CompareAction.tsx
- src/pages/ProfilesExplorerView/actions/FavAction.tsx
- src/pages/ProfilesExplorerView/actions/SelectAction.tsx
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneLayoutSwitcher.tsx
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneNoDataSwitcher.tsx
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneQuickFilter.tsx
- src/pages/ProfilesExplorerView/variables/GroupByVariable/GroupByVariable.tsx
- src/pages/ProfilesExplorerView/variables/ProfileMetricVariable.tsx
- src/pages/ProfilesExplorerView/variables/ServiceNameVariable.tsx
- src/shared/domain/reportInteraction.ts
See diff tab
- Once merged, we'll have to update our internal dashboard and see the new actions being tracked.
> feat(Analytics): Track Explore Profiles user actions

- .github/workflows/create-new-version.yml
> chore: ci fix

- .drone.jsonnet
Now that the build is stable we can enable this back
> chore: enable -latest update on release

- .github/workflows/create-new-version.yml
> ci(GitHubActions): Use Databases Frontend CI Bot email

- docs/sources/get-started/index.md
- docs/sources/investigate/index.md
Add link to the Explore Profiles' blog post and embed the video. 
Change a screenshot to show the correct one.
> docs: Add blog post link and video

- docs/sources/_index.md
Change the doc status from public to private. You need to have the doc URL to view the docs.
> docs: Change doc visibility

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
> chore(E2E): Upgrade Playwright to v1.46.0

- docs/sources/get-started/index.md
Corrected link to Explore Traces.
> docs: Fix link to Explore Traces

- .github/workflows/pr-validation.yml
See diff tab
- The "PR validation title" build check should pass
> build(PrValidationTitle): Add "build" task type

- Dockerfile.plugin.e2e
In last update to this [PR](https://github.com/grafana/explore-profiles/pull/157) in https://github.com/grafana/explore-profiles/pull/157/commits/4b6b48924872a6aff59b4eb0f67d64f73481b418 I forgot to update Docker file
Update Dockerfile.plugin.e2e to match package.json
> chore: Update playwright version

- docker-compose.remote.yaml
- docs/GRAFANA-CROSS-DEVELOPMENT.md
> docs(*): Update doc about using a local version of Grafana

- README.md
Just a quick update to reflect the current status of the app.
See diff tab
`-`
> docs(Readme): Getting Started update

- src/README.md
Update the plugin README to be consistent with the other Explore apps. 
Added a note that the plugin is a preview. 
> docs(*): Update plugin README

- .github/workflows/publish-technical-documentation-next.yml
- docs/sources/investigate/index.md
- src/README.md
N/A
Running `yarn run format:fix` in main updates these files.
Run `yarn run format:fix`. There should be no chagnes.
> chore: fix formatting

- src/pages/ProfilesExplorerView/components/SceneLabelValuesHistogram.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
- src/shared/components/QueryBuilder/ui/chiclets/Chiclet.tsx
- src/shared/components/QueryBuilder/ui/chiclets/ChicletAttributeOperator.tsx
- src/shared/components/QueryBuilder/ui/chiclets/ChicletAttributeOperatorValue.tsx
Just a small PR to add some improvements.
**Time series/histograms: changed the "total" legend in timseries/histograms**
**Filters: added ellipsis and tooltip to prevent long values to destroy the layout**
**Instrumented the filters to report when the query/filters change**
The build should pass.
> feat(*): Minor improvements

- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/SceneStatsPanel.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/CompareAction.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/StatsPanel.tsx
- src/shared/components/QueryBuilder/ui/chiclets/Chiclet.tsx
**Related issue(s):** follow-up of https://github.com/grafana/explore-profiles/pull/211
Some more minor updates.
|![image](https://github.com/user-attachments/assets/c7f09c10-81f2-4c5b-8fdf-e58aae3ac7bf)  | ![image](https://github.com/user-attachments/assets/d730a41d-e325-4a13-afab-c5f184abb54c) |
`-`
> feat(StatsPanel): Add title on hover value + vertical border to separate compare actions

- package.json
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/infrastructure/useFetchLlmPluginStatus.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/domain/useOpenAiChatCompletions.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/useOpenAiSuggestions.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/ui/Code.tsx
- yarn.lock
This PR to use the official `@grafana/llm` package instead of the `@grafana/experimental` one.
This PR also improves a bit the UI of the "Function details" panel:
| <img width="845" alt="Screenshot 2024-10-11 at 13 37 41" src="https://github.com/user-attachments/assets/459576a8-b153-431d-9842-d2a19437e6bb"> | <img width="847" alt="Screenshot 2024-10-11 at 13 36 10" src="https://github.com/user-attachments/assets/0f4c7fe5-52bd-4c2d-b0d2-6af45601e9b7"> |
See diff tab for specific comments.
Manually, by testing the AI features: "Explain flame graph" and "Optimize code"
> refactor(Ai): Add official LLM package

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/ui/ExplorationTypeSelector.tsx
| <img width="669" alt="image" src="https://github.com/user-attachments/assets/8bef3e3e-1d57-44cc-9c51-4292c3eaa4b3"> | <img width="667" alt="image" src="https://github.com/user-attachments/assets/1a3e479e-ac16-4aa7-8aa7-e25e9b2a25b5"> |
| <img width="668" alt="image" src="https://github.com/user-attachments/assets/a01d5735-54bf-41b8-9083-bca563205e56"> | <img width="670" alt="image" src="https://github.com/user-attachments/assets/abf7cc86-9be8-4760-95bd-d9a494ee5979"> |
See diff tab
`-`
> chore(Header): Add slight contrast to the exploration pills

- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
- src/shared/components/QueryBuilder/ui/chiclets/Chiclet.tsx
1. AI button: improved the message when the LLM plugin is misconfigured and when there's an error while checking if it's enabled or not.
2. Filters (aka query builder): fixed styles on hover a partial chiclet (before this PR, the mouse cursor was showing it's impossible to edit)
`-`
> fix(*): Small UI fixes

- src/app/components/Onboarding/ui/OnboardingModal.tsx
**Related issue(s):** fixes https://github.com/grafana/explore-profiles/issues/226
Just updating 2 links.
`-`
> fix(OnboardingModal): Change Grafana Agent to Grafana Alloy

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
Just a small fix for narrow screens
See diff tab
`-`
> fix(DiffView): Fix headers wrap

- docs/CONTRIBUTING.md
> docs(Contributing): Fix repo URL

- e2e/fixtures/pages/ExploreProfilesPage.ts
- e2e/tests/settings-view/settings-view.spec.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneExportMenu/SceneExportMenu.tsx
- src/pages/SettingsView/SettingsView.tsx
- src/shared/components/FlameGraph/components/ExportData.tsx
- src/shared/components/FlameGraph/components/ExportMenu.tsx
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/268
See diff tab
The build should pass
> feat(Export): Clarify that export to flamegraph.com will create a public URL

- docs/sources/choose-a-view/index.md
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneExportMenu/SceneExportMenu.tsx
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
- src/shared/domain/reportInteraction.ts
This PR to ensure we always use the customized version of `reportInteraction` + ensure that we use the correct interaction names.
See diff tab
`-`
> fix(Tracking): Use custom reporter

- package.json
- src/shared/infrastructure/tracking/faro/__tests__/faro.spec.ts
- src/shared/infrastructure/tracking/faro/faro.ts
- yarn.lock
We don't use it.
See diff tab
`-`
> refactor(Faro): Remove tracing instrumentation

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
[This PR's build](https://github.com/grafana/explore-profiles/pull/285) started to fail so... https://github.com/grafana/explore-profiles/tree/main/e2e#the-build-of-my-pr-has-failed-because-playwright-was-just-updated-how-to-fix-it
The build should pass
> build(Playwright): Upgrade to v1.49.0

- .drone.migration.jsonnet
- drone_migration.yaml
Follow-up after https://github.com/grafana/explore-profiles/pull/298. It's better to have formatted YAML to avoid auto-formatting on JSON (see also https://github.com/grafana/explore-profiles/pull/301) and YAML will be more readable to see applied changes.
Verify the output of yaml file is correct. No changes in runtime code to test.
> ci: Format drone migration yaml file

- .github/workflows/ci.yml
Fixes [#335](https://github.com/grafana/explore-profiles/issues/335)
Latest version of this PR got published so you can use it in your instance (version: ef3b31e9d79e2328867f8aa4d068646e503e9af9)
> ci: Update sha in version.ts

- e2e/tests/profile-types-view/profile-types.spec.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
- src/pages/SettingsView/SettingsView.tsx
- src/shared/domain/reportInteraction.ts
This PR:
- Specifies that the settings are not user settings, but **tenant** settings.
- Refactors our TS types related to user tracking
See diff tab.
> chore(*): A couple of cosmetic fixes

- .github/workflows/ci.yml
> ci: require running e2e before packaging

- .github/workflows/create-new-version.yml
> ci: permission to push tags

- .github/workflows/ci.yml
> ci: allow writing coverage report

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
> chore(EndToEnd): Upgrade Playwright to v1.50.0

- .github/workflows/create-new-version.yml
**Related issue(s):** follow-up of https://github.com/grafana/explore-profiles/pull/348
See diff tab
`-`
> ci(CreateNewVersion): Fix global URL

- .github/workflows/create-new-version.yml
> ci(CreateNewVersion): create and push new tag

- .github/workflows/create-new-version.yml
> ci: Use GitHub App in all actions

- .drone.jsonnet
- .drone.migration.jsonnet
- drone_migration.yaml
> ci: Publish to catalog only when build is running in main

- .github/workflows/deploy.yml
> ci: Fix deploy file name

- src/pages/AdHocView/ui/tabs/AdHocSingle.tsx
- src/shared/domain/reportInteraction.ts
See diff tab
- After merging this PR, the new events should appear on our dashboard
> chore: Track Ad Hoc view

- .github/workflows/change-version-in-plugins-catalog.yml
- .github/workflows/deploy-existing-version.yml
**Related issue(s):** #295 
Fixing issues returned by the validation.
CI should pass
> ci: Add missing props based on validation errors

- .github/workflows/cut-new-release.yml
- .github/workflows/release-existing-version.yml
**Related issue(s):** #295 
Changes flows to run jobs in sequence to keep more consistent state in case of errors.
> ci: Change flows to run jobs in sequence

- src/shared/infrastructure/tracking/faro/faro.ts
> fix(Faro): Narrow down frontend logging to plugin URL

- .github/workflows/change-version-in-plugins-catalog.yml
- .github/workflows/cut-new-release.yml
- .github/workflows/deploy-existing-version.yml
- .github/workflows/release-existing-version.yml
> ci: Make sure update-prod-catalog can be run

- .github/workflows/deploy-existing-version.yml
> ci: Change the cloud deployment workflow to allow deploying to specified environment

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/cut-new-release.yml
- .github/workflows/release-existing-version.yml
This is to make sure a sha is added when building a new version from a tag
> ci: Always use sha in version.ts

- .github/workflows/build.yml
> ci: Get correct sha for builds

- .github/workflows/deploy.yml
See also https://raintank-corp.slack.com/archives/C0671T2J5CH/p1739288563685579
This is to fix the error when running: https://github.com/grafana/explore-profiles/actions/runs/13266195626/job/37034724239
> ci: Update Trigger Argo Workflow actions

- .github/workflows/cut-new-release.yml
- .github/workflows/deploy-existing-version.yml
- .github/workflows/deploy.yml
> ci: Remove debug step and add emoji to important steps

- .github/workflows/cut-new-release.yml
As discussed it's preferable to run steps in sequence to avoid multiple points that can fail.
Not possible to test on a PR flow as it's part of the release workflow 🤷
> ci: Run deployments in sequence

- src/extensions/DeployPipelinesExtension.tsx
- src/extensions/IntegrationExtension.tsx
- src/pages/SettingsView/DeployIntegration.tsx
- src/pages/SettingsView/components/CollectorSettings/components/ViewRule/ViewRule.tsx
- src/plugin.json
changes reflecting the latest deploy-pipeliens extension changes: https://github.com/grafana/grafana-collector-app/pull/673
> feat: Jarben/deploy pipelines extension change

- src/pages/ProfilesExplorerView/domain/useGetPluginExtensionLink.ts
- src/plugin.json
Change pluginId of the investigations app. 
https://github.com/grafana/investigations-app/pull/175
> feat(investigations): adapt to changed plugin id

- src/plugin.json
👋 After the discussion, we are updating description to match the documentation https://grafana.com/docs/grafana/latest/explore/simplified-exploration/
> docs: update app description

- package.json
- yarn.lock
Fixes: #468
Upgrading to 0.12.0. Tried upgrading to 0.14.0 but the explain functions stopped working without any errors - needs a separate investigation
Explain Flame Graph should work as expected
> chore: Upgrade llm package

- package.json
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiReply.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/buildLlmSuggestionPrompts.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/useOpenAiSuggestions.ts
- yarn.lock
Fixes: #479 
We are passing empty content in `system` message prompt. Empty strings are now sent as nulls after https://github.com/sashabaranov/go-openai/pull/926 added in [1.37.0](https://github.com/sashabaranov/go-openai/releases/tag/v1.37.0). `go-openai` was updated in [grafana-llm-app](https://github.com/grafana/grafana-llm-app) in https://github.com/grafana/grafana-llm-app/pull/588 and after deployment optimize code in Profiles Drilldown stopped working.
- Use Grafana with latest version of [llm plugin](https://github.com/grafana/grafana-llm-app).
- Verify that Explain Flame Graph and Optimize Code return suggestions
> fix: Get suggestions for optimize code

- .github/workflows/cut-new-release.yml
- .github/workflows/upload.yml
- .github/workflows/zizmor.yml
> chore(ci): Fix possible template injections

- .github/workflows/cut-new-release.yml
- .github/workflows/release-existing-version.yml
Fixes incorrect paths added in https://github.com/grafana/profiles-drilldown/pull/517
> chore(CI): Fix paths to get GitHub app details

- .github/workflows/build.yml
- .github/workflows/bundle-stats.yml
- .github/workflows/ci.yml
- .github/workflows/update-plugins-catalog.yml
- .github/workflows/upload-pr.yml
- .github/workflows/upload.yml
- package.json
- yarn.lock
This is to simplify our config as we do not need to use GitHub repo secrets
> chore(ci): Stop using repo secrets

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
Updates Playwright to the latest version (required by E2E tests)
> chore: Update Playwright to 1.53.1

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
Small linting fix that keeps popping up
> chore: Fix Header linting

- Dockerfile.pyroscope.e2e
- buf.gen.yaml
- src/shared/pyroscope-api/settings/v1/recording_rules_pb.ts
- src/shared/pyroscope-api/types/v1/types_pb.ts
Updating to latest type definitions. I new optional property to allow passing function names was added. It will be used in #497
> chore: Update API type definitions

- .github/workflows/plugins-ci.yml
> ci: Deploy automatically to ops
