grafana/profiles-drilldown

- .github/workflows/pr-validation.yml
This PR configures the `ytanikin/PRConventionalCommits` GitHub Action to add a custom "docs" label.
See https://github.com/ytanikin/PRConventionalCommits?tab=readme-ov-file#example-usage-with-ticket-number-validation-and-custom-labeling
See diff tab
- The label that is automatically generated on this PR should be "type/docs" and not "docs"
> docs: Configure custom PR label 

- src/pages/ProfilesExplorerView/actions/CompareAction.tsx
Before this PR, when going from the "Labels" exploration type to the compare page, the data source query parameter was not passed. If there were multiple Pyroscope data sources, it could lead to a broken UI (e.g.):
See diff tab
- In an instance with multiple Pyroscope data sources configured
- Go to the "Labels" exploration type
- Select 2 label values for comparison
- Click "Compare" to open the "Comparison Diff View"
- The UI should always display correctly all the data, regardless of the data source that was selected
> fix(CompareAction): Add missing data source query parameter to compare URL

- src/pages/ProfilesExplorerView/variables/ProfilesDataSourceVariable.ts
- src/shared/infrastructure/http/ApiClient.ts
- src/shared/infrastructure/http/__tests__/ApiClient.spec.ts
**Related issue(s):** https://github.com/grafana/explore-profiles/issues/42
Now, when a user selects a different data source in the UI, it is stored in local storage.
This value is then used as default when the user revisits the Explore Profiles app.
Manually, in an instance with multiple data sources:
- Land on the page for the first time, select a different data source 
- Navigate to (e.g.) a dashboard
- Go back to Explore Profiles
- The data source that was selected in the 1st step is selected
> feat(DataSource): Persist the last selected data source

- src/plugin.json
This will enable the plugin automatically after install.
I also expose the repo and the issue tracker and updated the keywords.
Based on: https://github.com/grafana/explore-logs/blob/main/src/plugin.json
> feat: Update plugin metadata to auto enable 

- src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
|  <img width="433" alt="Screenshot 2024-07-22 at 15 13 41" src="https://github.com/user-attachments/assets/7e6c0019-5395-439b-bb9d-66b2b903ca65"> |  <img width="431" alt="Screenshot 2024-07-22 at 15 13 22" src="https://github.com/user-attachments/assets/4edf20ed-9d23-4d10-8c0e-8307ac9f5087"> |
See diff tab
`-`
> fix(PanelTitle): Remove series count when only 1 serie

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Before this PR, when expanding a panel, the series colors and legends were not preserved. This PR fixes this inconsistency.
**As a grid item:**
**After expanding the panel:**
| <img width="1266" alt="image" src="https://github.com/user-attachments/assets/53d1af9a-93d0-4732-bb67-722e30c7c4a2"> | <img width="1260" alt="image" src="https://github.com/user-attachments/assets/604e03d0-b3bd-468f-aeb4-0674e6f8810a"> |
See diff tab.
`-`
> fix(SceneLabelValuesTimeseries): Colors and legends are preserved on expanded timeseries

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
- src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
This PR is an enhancement to prevent extra grid renders when none of the grid items have changed. 
See diff tab for specific comments.
`-`
> fix(SceneByVariableRepeaterGrid): Prevent extra renders

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValueStat.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/88 and more
A couple of UI/UX improvements for the "Labels" exploration type:
- The "Select" action has been removed on panels with a single label value (further breakdown does not make sense)
- The "Compare" action has been removed when there's only a single panel in the grid (nothing to compare to)
- Bar gauges for single label values are not helpful (see https://github.com/grafana/explore-profiles/issues/88), they have been replaced by Stats visualizations, e.g.: 
- The "Bar gauge" button on the panel type switcher has been renamed to "Aggregate" (works for when the UI displays bar gauge or stat panels):
See diff tab for specific comments
- See related issue + manual testing in local after checking out …
> feat(Labels): Various UI/UX improvements

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
This PR fixes a small UI issue when the user lands on a grid with no items (e.g. "Favorites"):
| <img width="1705" alt="image" src="https://github.com/user-attachments/assets/867f404e-4155-4c5a-99fc-15b6ea55cacf"> | <img width="1701" alt="image" src="https://github.com/user-attachments/assets/342ad18a-f79f-49a8-bd7d-9b195e77db79"> |
`-`
- When there are no favorites in the browser's local storage, the "No results" + image should be displayed
> fix(Favorites): Render "No results" when there are no favorites

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
- src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
Just a quick PR to pull out some specific "groupBy" labels logic from `SceneByVariableRepeaterGrid`
See diff tab
- The build should pass 
- The `Labels` exploration view should work as before
> refactor(Labels): Move some "groupBy" logic out of SceneByVariableRepeaterGrid

- src/app/App.tsx
**Related issue(s):** follow-up of https://github.com/grafana/explore-profiles/pull/6 and https://github.com/grafana/explore-profiles/pull/20
The two PRs above introduced temporary redirections some time ago that we can now remove, assuming that our users have had some time to be aware of the changes.
See diff tab
- No more banners or redirection should occur when trying to access old URLs
> chore(App): Remove redirections to legacy pages

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
- src/pages/ProfilesExplorerView/components/SceneLabelValueStat.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
- src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
Whenever the UI displays a single timeseries, the total resource consumption is displayed in the legend:
This PR also does some refactorings to prepare the integration of the Comparison view.
See diff tab for specific comments
`-`
> feat(Timeseries): Add total resource consumption in legend

- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneLabelValuePanel.tsx
Seems to happen with Grafana 11.3:
| <img width="844" alt="image" src="https://github.com/user-attachments/assets/5936716d-c40d-4741-ac50-459b8bc6e381"> | <img width="845" alt="image" src="https://github.com/user-attachments/assets/9cbae1b2-3296-43d4-b7a8-16a967ae352d"> |
See diff tab.
`-`
> fix(SceneLabelValuePanel): Fix border color when baseline/comparison is selected

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
Fixes #116
Just an idea how we could approach #116 by hiding the labels for the data source picker and exploration type on smaller screens. It uses `xl` theme breakpoint (~1200px) which is a bit wider than needed (~1080px) so we can adjust it.
Load Explore profiles app and resize the window to below 1200px
Here's how it looks like:
https://github.com/user-attachments/assets/a51357f6-b329-4977-976e-26dd1d047eca
> fix(ScenesProfileExplorer): Make labels more responsive on smaller screens

- src/pages/ProfilesExplorerView/components/SceneAiPanel/SceneAiPanel.tsx
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/infrastructure/useFetchLlmPluginStatus.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiReply.tsx
- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/FollowUpForm.tsx
- src/pages/ProfilesExplorerView/components/SceneAiPanel/domain/buildLlmPrompts.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/domain/useOpenAiChatCompletions.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/ProfileApiClient.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/cleanupDotResponse.ts
- src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/useFetchDotProfiles.ts
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/components/SceneTimeRangeWithAnnotations.ts
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/infrastructure/useFetchDiffProfile.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
- src/shared/domain/useToggleSidePanel.ts
**Related issue(s):** is caused by https://github.com/grafana/explore-profiles/pull/119
This PR aims at fixing the "Explain Flame Graph" feature on the comparison view. Namely, before this PR:
- the `isDiff` prop [was not passed](https://github.com/grafana/explore-profiles/pull/119/files#diff-b648e06443c5667d8938e238e6b0a8b7579e793379e4fdd1cfc0c0191a7984e6R182) to the `AiPanel` component, leading to an incorrect AI analysis based solely on a single profile
- obtaining the queries required to fetch the profiles in DOT format relied on `parseLeftRightUrlSearchParams` which worked only for the legacy pages
To fix the issues, this PR introduces the new `SceneAiPanel` (based on the non-Scenes `AiPanel`), used both in `SceneFlameGraph` and `SceneDiffFlameGraph`.
See the diff tab for specific …
> fix(DiffFlameGraph): Fix the "Explain Flame Graph" (AI) feature

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/components/SceneTimeRangeWithAnnotations.ts
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
This PR adds the selected flame graph ranges in the "Diff flame graph" view (in the legend of each time series):
| <img width="1693" alt="Screenshot 2024-08-27 at 21 54 30" src="https://github.com/user-attachments/assets/c79342fe-b0ab-45a8-9205-0e8b73001419"> | <img width="1693" alt="Screenshot 2024-08-27 at 21 53 57" src="https://github.com/user-attachments/assets/dc2ac498-3d5d-46ac-85d6-15eb7b8a9d70"> |
Indeed, while navigating in time, users might "lose" this information.
See diff tab.
- Manually, after checking this branch locally
> feat(DiffFlameGraph): Add flame graph range in timeseries legend

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/types/GridItemData.ts
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesHistogram.tsx
- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
- src/pages/ProfilesExplorerView/helpers/panelBuilder.ts
**Related issue(s):** solves https://github.com/grafana/explore-profiles/issues/75
See diff tab
Manually, after checking this PR's branch locally:
- In the "Labels" view, by clicking on the new "Histograms" button
- After favoriting a panel, it should be displayed properly in the "Favorites" view
In both "Labels" and "Favorites", the expanded panel should be displayed properly (after clicking on the "expand" panel icon):
> feat(*): Add histogram visualizations

- CHANGELOG.md
- package.json
0.1.7 tag was pushed but the changelog and version bump was not updated in main in https://github.com/grafana/explore-profiles/actions/runs/10616320784 because I forgot to update protected branches settings. This should fix it by pushing missing change.
> chore: fix version and changelog for 0.1.7

- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/useCodeContainer.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/infrastructure/useFetchVCSFile.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/PrivateVcsClient.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/domain/types/FunctionDetails.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/infrastructure/fetchCommitsInfo.ts
**Related issue(s):** https://github.com/grafana/pyroscope-squad/issues/173
In this PR we introduce the usage of the root path. For the GitHub integration, it's a hint on where the sources are located inside the repository. More information at https://github.com/grafana/pyroscope/pull/3531
Just extracting the root_path from the version data that comes from the backend. Then send it back when searching for the file.
Run the rideshare example from this branch: https://github.com/grafana/pyroscope/pull/3531
Select in the flame graph some function related to the rideshare example to look at. The GetFile call should include the root_path "examples/language-sdk-instrumentation/golang-push/rideshare"
> feat: support submodules for GitHub Integration

- docs/sources/_index.md
Home page link to the Determine use case had a bad link to the troubleshooting section.
No issues. 
Fixes a broken link in the home page. 
Build the docs locally and click the link for Determine use case docs.
> docs: Fix broken link in docs

- Dockerfile.plugin.e2e
- e2e/README.md
- package.json
- yarn.lock
It seems that recent version of @playwright/test ([1.47.0](https://github.com/microsoft/playwright/releases/tag/v1.47.0)) modified where binaries are stored and we end up in version mismatch in [Dockerfile.plugin.e2e](https://github.com/grafana/explore-profiles/blob/daaef03086af712bde9e9d085323b83017f87e96/Dockerfile.plugin.e2e)
```
FROM mcr.microsoft.com/playwright:v1.46.0
RUN yarn add "@playwright/test@^1.46.0" "dotenv@^16.3.1"
```
This causes e2e tests to fail ([example](https://github.com/grafana/explore-profiles/actions/runs/10737014796/job/29777704251?pr=153))
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1134/chrome-linux/chrome
```
Also, based on latest release https://github.com/microsoft/playwright/releases/tag/v1.47.0: …
> chore: Upgrade @playwright/test to 1.47.0

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
N/A
Fixes a small warning showing up on startup:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `ExplorationTypeSelector`. See https://reactjs.org/link/warning-keys for more information.
at ExplorationTypeSelector (webpack-internal:///./pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx:16:36)
```
* Open dev tools
* Load the app
* The error should not show up
> chore: Add missing key to children component

- src/app/App.tsx
- src/shared/domain/__tests__/reportInteraction.spec.ts
- src/shared/domain/reportInteraction.ts
N/A
Adding version to all tracked events to better distinguish usage stats
Run following command in dev tools:
```
window._debug.echo.enable();
```
You should see the version being tracked as an extra property:
> chore: Add tracking to the version number for better insights on user stats

- src/shared/components/QueryBuilder/QueryBuilder.tsx
- src/shared/components/QueryBuilder/ui/hooks.ts
N/A
Fixes a warning thrown after selecting a filter:
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```
https://github.com/user-attachments/assets/b63a5cc9-67e4-42d7-a625-2806995bac22
We're calling blur() during the rendering which in this case should not lead to any nasty errors, but still it's a side effect so it's a bit cleaner if done after rendering finishes.
I've added `usePrevious` which is the same as the one coming with react-use. We can also consider adding react-use as a dependency if we take advantage of other hooks as well.
* Add a quick filter 
* The error should not show up in the dev console
> chore: Add and use usePrevious hook to fix side-effect errors

- src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
Just a quick fix to display the tooltip when the [Grafana LLM plugin](https://github.com/grafana/grafana-llm-app) is not installed: 
See diff tab.
Locally, for instance by commenting https://github.com/grafana/explore-profiles/blob/main/samples/provisioning-remote/plugins/app.yaml#L12-L30 and launching `yarn server:remote`
> fix(ExplainFlameGraph): Add tooltip when the LLM plugin is not installed

- docs/sources/_index.md
- docs/sources/get-started/index.md
Hides the Explore Profiles doc again until next week. Corrects the product name in a public preview amonition.
> docs(*): Fix issues in Explore Profiles docs

- src/shared/components/FlameGraph/components/ExportMenu.tsx
- src/shared/components/FlameGraph/components/domain/useExportMenu.ts
This PR fixes the error that occurs when trying to export a diff flame graph to pprof:
The export relies on using the legacy `query` parameter to fetch the profile in pprof format. But:
- it's incorrect because the diff profile depends on both baseline & comparison queries
- the `query` parameter has been deprecated when migrating the plugin to Scenes
The "pprof" export in the export menu should not be present anymore
> fix(DiffFlameGraph): Remove non-working pprof export

- Dockerfile.plugin.e2e
- e2e/README.md
- package.json
- scripts/upgrade-playwright
- yarn.lock
Just a small PR to simplify Playwright's ugrades.
This PR: 
- adds the new `upgrade-playwright` script
- uses it to upgrade Playwright to the latest version v1.47.1
`-`
> test(EndToEnd): Add new script to upgrade Playwright

- docs/sources/_index.md
Makes the docs public for the public preview launch. '
This PR should be merged when Explore Profiles goes live for customers. 
> docs(*): Make Explore Profiles docs public

- .github/workflows/publish-technical-documentation-next.yml
Each repository can only have 100 organization secrets and there are now more than 100 in our organization which causes inconsistent behavior.
Some repositories don't have the secrets they need assigned.
These composite actions use secrets stored in Vault that are available to all repositories.
- `publish-technical-documentation-next.yml` has been tested with https://github.com/grafana/writers-toolkit/blob/main/.github/workflows/publish-technical-documentation.yml.
**Special notes for your reviewer**:
There is some copy-paste involved in the creation of these workflows. Please check:
For `publish-technical-documentation-next.yml`:
> ci: Update workflows to use actions that don't need organization secrets

- README.md
This aligns with how we're going to message explore profiles at ObsCon, which is "in public preview for all grafana cloud and grafana open source users".
> docs: Update README.md to call out profiles as being in preview

- README.md
Related https://github.com/grafana/explore-profiles/pull/182
This leverages a more stylized version of markdown admonition.
Options are:
This is fine, but lacks emphasis.
Strikes a nice balance between emphasis but doesn't make it seem "dangerous".
Technically the appropriate level according to GitHub's [recommendation](https://github.com/orgs/community/discussions/16925#discussion-4085374), but I think it suggests using Explore Profiles is "dangerous," which is strictly not true as it remains quite stable.
> docs: Update readme markdown

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
- src/pages/ProfilesExplorerView/infrastructure/series/http/DataSourceProxyClient.ts
- src/shared/infrastructure/http/ApiClient.ts
- src/shared/infrastructure/http/__tests__/ApiClient.spec.ts
Fixes #188 
Using relative paths to Grafana API instead of pulling it directly from the config
See #188 for more details.
> refactor: Use relative URLs for API calls

- docs/sources/_index.md
- docs/sources/choose-a-view/index.md
Adds information about flame graph AI and the GitHub integration doc links to the Concepts page
Adds the intro video to the landing page
> docs: Add flame graph AI and intro video to doc

- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.tsx
- src/shared/components/QueryBuilder/domain/actions.ts
- src/shared/components/QueryBuilder/domain/helpers/__tests__/queryToFilters.spec.ts
- src/shared/components/QueryBuilder/domain/helpers/queryToFilters.ts
- src/shared/components/QueryBuilder/domain/types.ts
Fixes #199
Introduces a fixed value when `is-empty` operator is used to make sure the filter is considered complete and synced to the URL by scenes [here](https://github.com/grafana/scenes/blob/81ebbde10e4284a30eced804d246a930554a3bee/packages/scenes/src/variables/adhoc/AdHocFiltersVariableUrlSyncHandler.ts#L23) (isFilterComplete code [here](https://github.com/grafana/scenes/blob/f37965b46667cfa2d622dcd12d45e9910c0eabfb/packages/scenes/src/variables/adhoc/AdHocFiltersVariable.tsx#L360)).
1. Add a label and use `is empty` filter
2. Check if the `/query` request contains empty filter, e.g. `hostname=""`
3. Refresh the page
4. Check if the filter is preserved and `/query` request is correct
5. Add a different filter (e.g. `=`)
6. Edit the above filter and change it to …
> fix(Filters): ensure "is empty" filter is synced with URL

- src/shared/components/QueryBuilder/domain/helpers/__tests__/queryToFilters.spec.ts
- src/shared/components/QueryBuilder/domain/helpers/queryToFilters.ts
- src/shared/components/QueryBuilder/domain/states/loadLabelValues.ts
- src/shared/components/QueryBuilder/domain/types.ts
- src/shared/components/QueryBuilder/infrastructure/operatorsRepository.ts
- src/shared/components/QueryBuilder/ui/constants.ts
- src/shared/components/QueryBuilder/ui/inputs/SingleEditionInput.tsx
- src/shared/components/QueryBuilder/ui/selects/SingleEditionSelect.tsx
- src/shared/components/QueryBuilder/ui/selects/SingleSelect.tsx
**Related issue(s):** solves https://github.com/grafana/explore-profiles/issues/206, relates to https://github.com/grafana/grafana/issues/93664
The issue stems from the fact that the `Select` component from the [Saga design system](https://developers.grafana.com/ui/canary/index.html?path=/story/forms-select--basic) does not initialize its input with the value passed as prop. 
To circumvent the problem, this PR replaces the `Select` component by an HTML `input`. 
See the diff tab for specific comments.
Manually, by checking this PR ; here's a short video:
https://github.com/user-attachments/assets/041f85eb-f0da-49b8-8566-f87aa6d9f423
> fix(QueryBuilder): Filters with regex values can be edited in place

- docs/CODE-ARCHITECTURE.md
Added missing info that was lost when copy-pasting the Google doc in https://github.com/grafana/explore-profiles/pull/51
`-`
> docs(Contributing): Add missing domain logic layer doc

- Dockerfile.plugin.e2e
- package.json
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
- yarn.lock
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/196
This PR uses the [useChromeHeaderHeight hook](https://github.com/grafana/grafana/blob/612b86477265976eecdaaf1517d7748982a639fb/public/app/core/context/GrafanaContext.ts#L47-L58) to determine the correct `top` offset for the sticky app header.
Test with either:
- Grafana v11.3 or
- Grafana v11.2
In all the following cases, the Explore Profiles header should be positioned properly when scrolling:
- Toggle the top search bar on and off
- Switch to kiosk mode:
> fix(Header): Fix sticky header position in Grafana v11.3+

- src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
This PR persists the last service that was selected to localStorage so that, when coming back to the app, it is selected directly.
See diff tab.
Manually: going to Explore Profiles, selecting a service, going to (e.g.) a dashboard, then coming back to the app by clicking on the main menu item.
> feat(ServiceNameVariable): Persist last service selected in localStorage

- src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
I've noticed a weird bug on the "Diff flame graph view" where ranges were not preserved. Here are 2 short videos before/after:
| Before (currently in main) | After (what this PR fixes) |
| https://github.com/user-attachments/assets/2823fbc8-cd60-459c-a464-dc5ba2990d28 | https://github.com/user-attachments/assets/2e1be5cb-9fa8-40a8-9976-6920b4c2a250 |
Through `git bisect` I was able to pinpoint [this commit](https://github.com/grafana/explore-profiles/commit/39176600a4c260aa33499635954df5174fc6a54a) as the culprit.
To be totally honest, I still don't fully understand why it happened and why this PR fixes it.
- Locally, after checking out this PR
> fix(DiffView): Ensure ranges are initialized when landing

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
- src/pages/SettingsView/domain/__tests__/useSettingsView.spec.ts
- src/pages/SettingsView/domain/useSettingsView.ts
This PR fixes the following bug:
- Go to the "Settings" view
- Modify the maximum number of nodes
- Save the settings
- Click on the "Back to Explore Profiles" button
- Go to the "Flame graph" view
**Actual behaviour:** the new maximum number of nodes is not applied
**Expected behaviour:** the new maximum number of nodes is applied
See diff tab for specific comments.
1. The build should pass
2. Manually, after checking out this PR on your local machine.
> fix(SettingsView): Fix back button after modifying the max nodes setting

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/__tests__/builsShareableUrl.spec.ts
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/builsShareableUrl.ts
When the default time range is selected and not modified, the shareable link does not work: there are no absolute `from`/`to` URL search parameters in the shareable URL. This PR fixes it.
See diff tab
- The unit tests should pass
> fix(ShareableUrl): Fix link generation when the default time range is selected

- .github/workflows/ci.yml
- package.json
- yarn.lock
Adds a BundleWatch task to our CI.
Adds [BundleWatch](https://bundlewatch.io/#/) to our build. This is so we can keep an eye on our module.js (bundle) size in case there is any unexpected jumps between PR's. Overall this allows us to keep our bundle size down for performance reasons.
Allow the PR build to run and check the output.
> build(Bundle): Add BundleWatch to CI

- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
**Related issue(s):** is caused by https://github.com/grafana/explore-profiles/pull/249
This PR makes the scale persistent when the timeseries data changes (e.g. when choosing a different time range/adding filters).
See diff tab
- Go to (e.g.) the "Flame graph view"
- Change the scale to "Log2"
- Choose a different time range
- Add some filters
Expected behaviour: the timeseries should display the data with a "Log2" scale
> fix(Timeseries): Persist scale when data changes

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/ui/ExplorationTypeSelector.tsx
Just a small cosmetic fix for the background color of the connecting lines:
| <img width="444" alt="image" src="https://github.com/user-attachments/assets/9f702612-ec03-4ccc-a869-42664c324144"> | ![image](https://github.com/user-attachments/assets/e60f1a7e-2e42-4ec3-be63-af7640531713) |
See diff tab
`-`
> fix(ExplorationSelector): Fix background color

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
**Related issue(s):** fixes https://github.com/grafana/explore-profiles/issues/253
See diff tab
Manually:
- clicking on "Auto-select" should always select a 25% range on both the baseline & the comparison time series
- when the 25% are bigger than one day, the range should be capped to 1 day
> fix(DiffView): Clicking on "Auto-select" selects a 25% range

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/ScenePresetsPicker/ScenePresetsPicker.tsx
**Related issue(s):** is caused by https://github.com/grafana/explore-profiles/pull/254
The logic was changed in the linked PR, but the corresponding preset option was not updated. This PR fixes it.
`-`
> fix(DiffView): Fix incorrect preset label

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
**Related issue(s):** is caused by https://github.com/grafana/explore-profiles/pull/231/files#diff-b648e06443c5667d8938e238e6b0a8b7579e793379e4fdd1cfc0c0191a7984e6R105
A quick fix to properly disable the "Explain Flame Graph" when no selections are made
See diff tab
`-`
> fix(DiffView): Disable AI button when no selections

- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/__tests__/filter-ops.spec.ts
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.ts
See diff tab
- Manually by loading the page after altering the filters URL search parameter
> fix(QueryBuilder): Prevent invalid filters to be used after parsing URL

- src/pages/ProfilesExplorerView/components/SceneExploreAllServices/SceneExploreAllServices.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneExploreServiceFlameGraph.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneExploreServiceLabels.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceProfileTypes/SceneExploreServiceProfileTypes.tsx
- src/pages/ProfilesExplorerView/domain/actions/SelectAction.tsx
- src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
- src/shared/domain/__tests__/reportInteraction.spec.ts
- src/shared/domain/reportInteraction.ts
This PR fixes a couple of issues related to tracking. The major one being that, because the symbol names are minified in production, so are the classes names. Thus the `SelectAction` Scene object can't rely on it.
See diff tab for specific comments
The build should pass
> fix(Tracking): Ensure select action type is tracked

- src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
Fixes: #283
In https://github.com/grafana/explore-profiles/pull/222 we introduced loading last used service name from local storage. The stored value is applied during `onActivate()` (it was changed in https://github.com/grafana/explore-profiles/pull/233). This however overrides the service name value if it's provided in the URL. The change is to skip loading last used service name if it's already set (e.g. from the URL)
See reproduction steps in #283
> fix(ProfileTypesView): Load last used service name only if it's not provided in the URL

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
- src/shared/components/SceneTimePickerWithoutSync/SceneTimePickerWithoutSync.tsx
Temporarily disable time range sync introduced in https://github.com/grafana/grafana/pull/94074 until scenes allow to control it.
Modifies SceneTimePicker to pass `isSync` property disabling the sync.
Check if there's no additional sync button in Diff Flame Graph view
> fix(SceneComparePanel): Temporarily disable time range sync

- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
- src/pages/ProfilesExplorerView/helpers/__tests__/getExploreUrl.spec.ts
- src/pages/ProfilesExplorerView/helpers/getExploreUrl.ts
- src/shared/domain/reportInteraction.ts
**Related issue(s):** relates to https://github.com/grafana/explore-profiles/issues/299, blocks https://github.com/grafana/explore-profiles/pull/301
This PR adds a new "Open in Explore" menu item to each time series in the app:
This is a preliminary PR before adding the support to Investigations. I took the opportunity to add some missing tracking (for the type of scale).
See diff tab for specific comments.
The build should pass
> feat(Timeseries): Add open in Explore menu item

- src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
- src/pages/ProfilesExplorerView/infrastructure/timeseries/buildTimeSeriesQueryRunner.ts
- src/shared/domain/reportInteraction.ts
**Related issue(s):** relates to https://github.com/grafana/explore-profiles/pull/301
A quick preparation PR in order to support Investigations in Explore Profiles.
The changes are mainly scoped to `SceneLabelValuesTimeseries`
> refactor: prepare Investigations support

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/domain/sortFavGridItems.ts
- src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
- src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
- src/pages/ProfilesExplorerView/infrastructure/series/formatSeriesToProfileMetrics.ts
- src/pages/ProfilesExplorerView/infrastructure/series/formatSeriesToServices.ts
- src/shared/components/QueryBuilder/ui/selects/MultipleEditionSelect.tsx
- src/shared/domain/localeCompare.ts
**Related issue(s):** see https://github.com/grafana/grafana/pull/96862 for performance impact
A PR just to modernize our code base by using the [Intl APIs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator).
See diff tab.
> refactor(*): Use the Intl API for sorting items

- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/306
Prevent this fatal error to happen:
Just be gracefully falling back to a 0 value.
See diff tab.
- In Grafana < v11.3, no fatal error should occur
> fix(Header): Prevent crash if useChromeHeaderHeight is not available (for Grafana < v11.3)

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/ScenePresetsPicker/ScenePresetsPicker.tsx
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/309
To prevent confusion, this PR ensures that the preset option is cleared after selecting an "Auto-preset". See the linked issue for more details. 
See diff tab
- `-`
> fix(DiffFlameGraphView): Clear preset option when applying auto-select

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/infrastructure/buildCompareTimeSeriesQueryRunner.ts
- src/pages/ProfilesExplorerView/infrastructure/flame-graph/buildFlameGraphQueryRunner.ts
- src/pages/ProfilesExplorerView/infrastructure/timeseries/buildTimeSeriesQueryRunner.ts
- src/pages/ProfilesExplorerView/infrastructure/withPreventInvalidQuery.ts
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/314
| <img width="1402" alt="image" src="https://github.com/user-attachments/assets/48872e5b-3663-4d0b-bab6-9f3d21b8750a" /> | <img width="1407" alt="image" src="https://github.com/user-attachments/assets/68632927-6d7d-4deb-9f68-c935073a159e" />|
This PR adds an activation handler to each query runner being instantiated. The handler is validating the query being passed so that, if either no service name or profile type is defined, no query is executed.
See the the linked issue above:
- The Network tab should not show any `query=ds=xxx` (failing) HTTP requests.
- The UI should not show any error icon on the timeseries panels, "No data" should be displayed instead
Be …
> fix(QueryRunners): Prevent invalid queries to run

- src/app/components/Routes/Routes.tsx
- src/pages/AdHocView/AdHocView.tsx
- src/pages/ProfilesExplorerView/ProfilesExplorerView.tsx
- src/pages/SettingsView/SettingsView.tsx
Reverts grafana/explore-profiles#322 after deploying in ops and seeing:
Will need to check our build pipeline if we want this optimization.
> revert: "perf(*): Lazy load page components"

- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubRepository.tsx
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/35
See diff tab
`-`
> feat(GitHubIntegration): Add info tooltip on connect button

- package.json
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
- src/shared/components/FlameGraph/FlameGraph.tsx
- yarn.lock
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/260, related PR in Grafana https://github.com/grafana/grafana/pull/98356
This PR introduces a new `keepFocusOnDataChange` prop to the `FlameGraph` component.
See the linked PR in Grafana
- Manually:
- Go to the "Flame graph" or the "Diff flame graph" view
- Click on a flame graph node
- Click on "Focus block"
- Change the time range or click on the time picker refresh button
- The block should stay focused and the percentage should update or drop to 0 if the function didn't consume any resource for the new time range
The same should occur for the sandwich view
> feat(FlameGraph): Keep items focused when data changes

- src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
This PR prevents an unexpected behaviour by always disabling the time ranges sync before applying a preset:
https://github.com/user-attachments/assets/31cd77ec-8ff6-43da-88b4-41453216706d
See diff tab
Manually:
- Enable time range sync
- Either choose "Auto-select" when landing on the "Diff flame graph" view or
- Choose a preset
- The sync should be disabled **before** the preset is applied
> fix(DiffFlameGraph): Always disable time ranges sync before applying a preset

- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/domain/__tests__/convertPprofToFunctionDetails.spec.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/domain/convertPprofToFunctionDetails.ts
- src/shared/types/PprofProfile.ts
When this code looked up function detail, it only took a look at the first line of a location. A location with multiple lines happens when functions are inlined, the last entry represents the caller into which the preceding entries were inlined into.
This corrects this problem and allows to find function detail in this case as well.
Reported by @colega
> fix(GitHubIntegration): Handle function details for inlining

- src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
Prevents non-friendly display issues when (e.g.) a variable loading error comes as an object `{refId, message, status}`:
See diff tab
No more `[object Object]` message displayed if a query fails
> fix(Grid): Fix error message display

- .github/workflows/ci.yml
Fixes #366
Make sure signing the plugin happens only in main to allow running CI in forks.
Run the job, e.g. https://github.com/grafana/explore-profiles/actions/runs/13041161764/job/36383129066 to see signing is being skipped:
> ci: Prevent signing and publishing the plugin in forked repos

- .github/workflows/ci.yml
- .github/workflows/deploy-existing-version.yml
**Related issue(s):** #346 
Fixes incorrect paths / refs updated in [the last commit](https://github.com/grafana/explore-profiles/pull/364) of https://github.com/grafana/explore-profiles/pull/364. It was supposed to use main branch workflows but:
- the ref needs to be specified if `owner/repo` format is used
- the ref can be skipped for workflows in the same repo but path needs to be relative
See docs in: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow
- Use a relative path to a reusable workflow
Workflows should be running for the PR (https://github.com/grafana/explore-profiles/actions/runs/13114010650)
> ci: Use refs for reusable workflows

- e2e/tests/flame-graph-view/github-integration.spec.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/SceneFunctionDetailsPanel.tsx
**Related issue(s):** resolves https://github.com/grafana/explore-profiles/issues/353
Just adding [this hack](https://stackoverflow.com/questions/27957443/strange-special-characters-issue-in-left-side-ellipsis)
- See the issue linked above
> fix(FunctionDetailsPanel): Fix start ellipsis for file names containing non-alpha chars

- src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
- src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
- src/pages/ProfilesExplorerView/domain/variables/ProfilesDataSourceVariable.ts
- src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
Before this PR, the filters were not always reset when changing the data source.
See diff tab
Manually, for instance:
1. Go to the "Diff flame graph" view and add baseline and comparison filters
2. Go to the "All services" view
3. Change the data source
4. Go back to the "Diff flame graph" view
5. The filters have been cleared
Also:
- The filters should be cleared when changing the service in the "Labels" view and coming back to the "Diff flame graph" view
> fix(Filters): Ensure filters are always cleared when changing the data source or the service

- src/shared/infrastructure/settings/settingsApiClient.ts
> fix(Settings): Prevent warning to be displayed when no settings is returned by the Settings API

- docker-compose.e2e.yaml
- docker-compose.local.yaml
- docker-compose.remote.yaml
- docker-compose.yaml
**Related issue(s):** follow-up of https://github.com/grafana/explore-profiles/pull/386
See diff tab
Locally:
- Update the npm package version in `package.json` to e.g. `1.0.0`
- In a terminal, execute e.g. `yarn server:static`
- Grafana starts correctly and, on the UI, clicking on the info tooltip in the app header shows "Explore Profiles v1.0.0"
> ci(Docker): Disable all plugin preinstalls to prevent clashes

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/create-new-version.yml
**Related issue(s):** #295 
Newly created flow to create a new version runs redundant e2e tests that should be passing in main.
E2E tests should be run for this PR.
> ci: Disable e2e when creating a new version

- .github/workflows/build.yml
This is to avoid errors in main:
> [Build and test / Frontend build](https://github.com/grafana/explore-profiles/actions/runs/13267415669/job/37038277530#step:8:26)
Resource not accessible by integration - https://docs.github.com/rest/commits/comments#create-a-commit-comment
Example: https://github.com/grafana/explore-profiles/actions/runs/13267415669
> ci: Run test coverage only in pull requests

- docker-compose.e2e.yaml
- docker-compose.local.yaml
- docker-compose.remote.yaml
- docker-compose.yaml
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
This PR ensure the UI always displays an error message when loading profile data fails, for instance:
| <img width="1699" alt="Screenshot 2025-02-12 at 13 30 50" src="https://github.com/user-attachments/assets/9b92a420-8099-468e-a374-e733727a6289" />  |  <img width="1694" alt="Screenshot 2025-02-12 at 13 32 25" src="https://github.com/user-attachments/assets/a58f5fb4-42e3-472c-b00f-96bf8538fd13" />|
See diff tab
- When loading profile data fails, the UI always displays an error message
> fix(FlameGraph): Always render an error message when loading fails

- .github/workflows/ci.yml
Even after adding https://github.com/grafana/explore-profiles/commit/6bf120fb589e191affa1c45226eac77d98a5e0ae the commit created by the release workflow still triggers CI workflow - https://github.com/grafana/explore-profiles/actions/runs/13285546395. 
This puts it in step with what other apps are doing (example: https://github.com/grafana/log-volume-explorer/blob/5acaf4dcedcec3af0710fc2eb744e5086aad234a/.github/workflows/ci.yml#L19)
The CI in the PR should work as expected. The actual change we can test only with the actual release workflow.
> ci: Use correct github.actor to prevent CI builds on tags

- .github/workflows/deploy.yml
Argo workflow ids need to be unique. If we want to roll back a version that had been deployed with Argo workflow before by using a new Argo workflow run we need to make sure the name is unique.
Otherwise this happens: https://github.com/grafana/explore-profiles/actions/runs/13290554925/job/37110024616
Failed to submit workflow: rpc error: code = AlreadyExists desc = workflows.argoproj.io ...  already exists, the server was not able to generate a unique name for the object
Can be tested after merging to main - dev flow will be triggered
> ci: Trigger unique Argo workflows

- .github/workflows/deploy.yml
This didn't work https://github.com/grafana/explore-profiles/pull/414 because of  https://github.com/grafana/explore-profiles/actions/runs/13291594115/job/37113913511
```
Failed to submit workflow: rpc error: code = InvalidArgument desc = workflow name \"deploy-plugin-dev-cfcbb7e1e5e84f224323fd6af619f06e7d0f97ac-13291594115-1\" must not be more than 63 characters long (currently 72)
```
Truncating to 10 characters. 7 is a short sha but also v0.0.10 is 7 characters long so giving a bit more to take longer version numbers into account. We may need something more robust though but I don't want to complicate things at the same time :/ 
Same as #414 - we can test with dev flow from main
> ci: Use shorter sha for Argo workflows

- src/app/Routes.tsx
**Related issue(s):** relates to https://github.com/grafana/explore-profiles/pull/324
After trying to rollback to a previous version of the plugin, we've noticed many "Loading chunk 75 failed" errors in the browser (~25 for a single user!). 
To prevent this situation to happen, this PR removes the lazy loading of the page components introduced in https://github.com/grafana/explore-profiles/pull/324.
See diff tab
- After merging and deploying, rolling back to a previous version should not cause any error in the user browser
> fix(*): Remove lazy loading of page components

- e2e/fixtures/pages/ExploreProfilesPage.ts
- src/app/Routes.tsx
Our logs show a small amount of visits to non-supported paths. This PR adds an explicit redirection for these.
See diff tab
`-`
> fix(Routes): Add redirection for non-supported paths

- .github/workflows/cut-new-release.yml
The creation of the GitHub release for our first major version (`v1.0.0`) worked, but the release notes were incorrect. This PR fixes it.
This PR updates the regular expression used by `awk` to extract the most recent changes from the changelog file.
- Manually, by executing `awk '/^(#+ \[)/ {s++} s == 1 {print}' CHANGELOG.md` in a terminal for various changelogs
> ci: Fix GitHub release creation of a major version

- .github/workflows/ci.yml
- .github/workflows/cut-new-release.yml
**Relates to:** #295 
Currently some name don't have labels and show up as "deploy-to-dev", etc.
This PR is to add some labels aligned with CI workflow
> ci: Add labels to CI jobs

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
Fixes: #452
Run: `./scripts/upgrade-playwright 1.50.0 1.51.0`
E2E tests should pass
> chore(EndToEnd): Update Playwright to v1.51.0

- README.md
Readme was mostly updated but it looks like we were still saying that this app was nested under "Explore" even though now its under "Drilldown".
> docs: Update the readme for Drilldown with proper navigation instructions

- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/ui/GitHubIntegrationBanner.tsx
The only valid label name is `service_git_ref`.
Was highlighted by @Alex3k in [slack](https://raintank-corp.slack.com/archives/C03NCLB4GG7/p1741684699066899)
> docs: Fix label name for service_git_ref

- buf.gen.yaml
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/CodeContainer.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/__tests__/annotateLines.spec.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/__tests__/buildLineProfiles.spec.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/annotateLines.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/buildLineProfiles.ts
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/useCodeContainer.ts
Currently, we only use the snippet of code displayed to the user as context for the LLM prompt. This has the downside of making the LLM reason with less information. If we pass the entire file (if we have it) to the LLM prompt, this should improve its reasoning ability and give users the chance to ask follow up questions about portions of the code which might be in the same file, but not in the profiling snippet.
Here's an example of a short code snippet in a large file:
When asked about code in a different part of the same file, the LLM reports it can only reason about the current snippet:
With the changes in this PR, the LLM can now reason about the the entire file. Here's a snippet that's part of a larger file:
And here is the LLM's response to asking about a specific part of the file …
> fix(FlameGraph): Use entire file as context in "Optimize Code" prompt

- src/shared/infrastructure/settings/settingsApiClient.ts
- src/shared/infrastructure/settings/useFetchPluginSettings.ts
Fixes: #467
Ensure base URL is recreated for settings when fetching + when data source changes the query is retriggered.
Looks for `/api/datasources/proxy/uid/[DATASOURCE_UID]/settings.v1.SettingsService/Get` calls in network tab. The `[DATASOURCE_UID]` should be updated after changing the data source.
Before:
https://github.com/user-attachments/assets/c3ee7581-56cf-409c-afdf-be5d1061dcbb
After:
https://github.com/user-attachments/assets/0ec49778-20f8-4462-8cba-4fd54429ac83
> fix(Settings): Reload settings when data source changes

- src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/domain/__tests__/useBuildServiceNameOptions.spec.ts
- src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/domain/useBuildServiceNameOptions.ts
Assuming there is an overlap of services on different levels in the service_name hierachie, the app crashses.
I created that example by having two profiles series:
- `my-service`
- `my-service/my-subservice`
I have reimplemented the function sorting the services names first and then building up a hierarchic map, which should also be faster.
What is not ideal yet, is that it is not clear which one of the two is the one with children vs. the main one:
> fix: Cascader options break when services have multiple levels with matching prefix

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/update-make-docs.yml
- README.md
- docs/CONTRIBUTING.md
- docs/GRAFANA-CROSS-DEVELOPMENT.md
- docs/README.md
- src/README.md
- src/plugin.json
- src/shared/components/QueryBuilder/ui/inputs/SingleEditionInput.tsx
- src/shared/pyroscope-api/vcs/v1/vcs_pb.ts
- src/shared/ui/PluginInfo.tsx
Renames references to the repo name with the name
The build should pass and the app should load normally. Links to repo in plugin info should work as expected.
> chore: Update repo name references after the rename

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
Updating Playwright to the latest version.
See failing e2e tests in https://github.com/grafana/profiles-drilldown/actions/runs/14533618425/job/40777983376?pr=471
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium_headless_shell-1169/chrome-linux/headless_shell
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.52.0. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.51.0-noble               ║
║ - required: mcr.microsoft.com/playwright:v1.52.0-noble               ║
║                                                                      ║
║ <3 Playwright Team …
```
> chore(e2e): Update Playwright to 1.52.0

- .github/workflows/cut-new-release.yml
- .github/workflows/release-existing-version.yml
- .github/workflows/upload.yml
Fixes issues when uploading https://github.com/grafana/profiles-drilldown/actions/runs/14659481025/job/41140864301
Upload GitHub action uploads to GCS + GitHub artifacts, but we cannot create artifacts with the same name. The GitHub artifact is now used only for creating a GitHub release so we can actually run it only when making a new release.
> chore(ci): Fix uploading artifacts

- src/app/Root.tsx
- src/module.ts
Fixes: #423 
See https://raintank-corp.slack.com/archives/C048VSWPZ4P/p1745522343367069
This lazily loads the Profiles Drilldown app so it doesn't negatively impact other pages within Grafana. Example of loading a blank dashboard (having nothing to do with Profiles Drilldown) which loads the entire Profiles Drilldown app.
> feat: Lazy load entire app

- .github/workflows/cut-new-release.yml
- .github/workflows/release-existing-version.yml
Uses newly created GitHub app to perform release tasks:
- committing the changelog and tagging
- creating a github release
> chore(CI): Use new GitHub app for releases

- .github/workflows/ci.yml
- .github/workflows/cut-new-release.yml
- Fixes the name used to check branch protection rules
- Updates the email (though it's not used for protection rules)
- Updates skipping CI workflow when changes are triggered by the release
> chore(CI): Fix app name used when committing

- e2e/config/constants.ts
- e2e/fixtures/pages/ExploreProfilesPage.ts
- e2e/tests/settings-view/settings-view.spec.ts
- src/pages/ProfilesExplorerView/components/SceneCreateMetricModal/SceneCreateRecordingRuleModal.tsx
- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
- src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
- src/pages/RecordingRulesView/RecordingRulesView.tsx
- src/shared/types/RecordingRuleViewModel.ts
Fixes: https://github.com/grafana/profiles-drilldown/issues/498
Related issue(s): https://github.com/grafana/pyroscope-squad/issues/398
When clicking on the Prometheus icon the user can add a new recording rule. Depending on the exploration type it will use following data to populate the modal:
- All services: No service name + selected profile type
- Profile types: selected service name + **first profile type from the list**
- Labels / Flame Graph / Diff: selected service name + profile type
- Favorites: No service name + **first profile type from the list**
https://github.com/user-attachments/assets/7ea17cb7-b98b-4a69-9247-e2275b5bcb88
> feat(Metrics from Profiles): Allow creating recording rules for all services

- src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/GitHubContextProvider.tsx
Fixes: https://github.com/grafana/profiles-drilldown/issues/514
Keeps the auth cookie within the same session unless data source is changed. The user can refresh the page, navigate between various Grafana pages easily without the need to re-authenticate again.
Before:
https://github.com/user-attachments/assets/e9da0a65-69f7-40db-8d65-35eede505482
After:
https://github.com/user-attachments/assets/9dfe5a92-192b-4fa0-a54c-3fd4568e1a2e
Set up GitHub integration (you can read more in https://grafana.com/docs/grafana-cloud/monitor-applications/profiles/pyroscope-github-integration/):
- Create a GitHub App (not OAuth app) in https://github.com/settings/apps
- Copy clientID and create a new client secret
- Use `http://localhost:3000/a/grafana-pyroscope-app/github/callback` as callback URL 
- Set …
> feat(GitHub Integration): Keep GitHub auth cookie within the same session if the data source doesn't change

- Dockerfile.plugin.e2e
- package.json
- yarn.lock
Upgrading to latest Playwright, required by our CI/CD pipelines.
> chore: Upgrade Playwright to 1.54.1

- e2e/fixtures/pages/ExploreProfilesPage.ts
- e2e/tests/recording-rules/recording-rules.spec.ts
- e2e/tests/settings-view/settings-view.spec.ts
- samples/static/pyroscope/config.yaml
- src/pages/ProfilesExplorerView/components/SceneCreateMetricModal/SceneCreateRecordingRuleModal.tsx
Related issue(s): #497
While working on #497 I figured I would need to add more e2e tests and realized some basic end to end scenario is missing. Creating a separate PR - this will reduce changes introduced for #497.
Tests from settings-view were extracted to a separate file + "Create and display" test was added.
Tests should pass
> chore(e2e): Full flow e2e test for creating recording rules

- .github/workflows/plugins-pr.yml
- .github/workflows/plugins-release.yml
This will allow us to publish PRs for testing (previously done with upload label). To unlock [the full flow ](https://raintank-corp.slack.com/archives/C075BDBTX96/p1752223206316099?thread_ts=1752168379.983589&cid=C075BDBTX96)we also need https://github.com/grafana/hosted-grafana/pull/6698 merged.
> ci: Add a workflow to publish a PR/branch

- src/plugin.json
Add missing target from https://github.com/grafana/profiles-drilldown/pull/593
> chore: Add missing target to plugin.json
